services:
  artisantz_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: artisantz-app:latest
    container_name: artisantz-app
    restart: always
    ports:
      - "8002:80"
    env_file:
      - .env
    networks:
      - workshop_network

networks:
  workshop_network:
    external: true
    name: workshop-playit20262_workshop_net
